---
- name: Vector | install Vector distrib
  ansible.builtin.yum:
    name: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    state: present
  tags: vector
- name: Vector | Create directory for Vector logs
  ansible.builtin.file:
    state: directory
    path: /var/lib/vector/local_logs
    mode: 0755
  tags: vector
- name: Vector | Template config
  ansible.builtin.template:
    src: vector.yml.j2
    dest: /etc/vector/vector.yml
    mode: 0755
    owner: root
    group: root
  tags: vector
- name: Vector | create systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: 0755
    owner: root
    group: root
  tags: vector
- name: Vector | Start service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true
  tags: vector
