---
- name: Vector | install Vector distrib | CentOS
  become: true
  ansible.builtin.yum:
    name: "{{ vector_url }}"
    state: present
  when: ansible_distribution == "CentOS"
  tags: vector
- name: Vector | install Vector distrib | Ubuntu
  become: true
  ansible.builtin.apt:
    deb: "{{ vector_deb }}"
  when: ansible_distribution == "Ubuntu"
- name: Vector | Create directory for Vector logs
  become: true
  ansible.builtin.file:
    state: directory
    path: /var/lib/vector/local_logs
    mode: 0755
  tags: vector
- name: Vector | Template config
  become: true
  ansible.builtin.template:
    src: vector.yml.j2
    dest: /etc/vector/vector.yaml
    mode: 0755
    owner: root
    group: root
    validate: vector validate --no-environment --config-yaml %s
  tags: vector
- name: Vector | create systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: 0755
    owner: root
    group: root
  tags: vector
- name: Vector | Start service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true
  when: ansible_virtualization_type != "docker"
  tags: vector
